version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: iot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: iot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - iot-network

  # Uncomment this section if you want to run your NestJS app in Docker too
  # app:
  #   build: .
  #   container_name: iot-app
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #     - DB_HOST=postgres
  #     - DB_PORT=5432
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=123456
  #     - DB_NAME=iot_db
  #   depends_on:
  #     - postgres
  #   networks:
  #     - iot-network

volumes:
  postgres_data:

networks:
  iot-network:
    driver: bridge
